config/routes.rb
Mormonizer::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  namespace :admin do
    root :to => "translations#index"
    resources :translations
    resources :users
    resources :languages
  end

  resources :translations
  root :to => "translations#index"
end

app/models/language.rb
# Stores a collection of words that are applied to a translation to edit the input text
class Language < ActiveRecord::Base
  has_many :translations

  has_many :words
  accepts_nested_attributes_for :words, :allow_destroy => true

  validates_presence_of :name

  # Translate text based on the words of the language
  #
  # Note that this translates the words in arbitrary order so if two words match the same string
  # it is not clear which one will do the actual translating
  #
  # @param [String] input_text The text to translate
  # @param [String] The translated text based on applying each word's translation to the text
  def translate(input_text)
    output_text = input_text
    self.words.each do |word|
      output_text = word.translate(output_text)
    end
    return output_text
  end

end

app/controllers/admin/languages_controller.rb
module Admin
  class LanguagesController < ApplicationController
    load_and_authorize_resource

    # GET /admin/languages
    def index
      @languages = Language.all

      respond_to do |format|
        format.html # index.html.erb
      end
    end

    # GET /admin/languages/1
    def show
      @language = Language.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
      end
    end

    # GET /admin/languages/new
    def new
      @language = Language.new

      respond_to do |format|
        format.html # new.html.erb
      end
    end

    # GET /admin/languages/1/edit
    def edit
      @language = Language.find(params[:id])
    end

    # POST /admin/languages
    def create
      @language = Language.new(params[:language])

      respond_to do |format|
        if @language.save
          format.html { redirect_to admin_language_path(@language), notice: 'Language was successfully created.' }
        else
          format.html { render action: "new" }
        end
      end
    end

    # PUT /admin/languages/1
    def update
      @language = Language.find(params[:id])

      respond_to do |format|
        if @language.update_attributes(params[:language])
          format.html { redirect_to admin_language_path(@language), notice: 'Language was successfully updated.' }
        else
          format.html { render action: "edit" }
        end
      end
    end

    # DELETE /admin/languages/1
    def destroy
      @language = Language.find(params[:id])
      @language.destroy

      respond_to do |format|
        format.html { redirect_to admin_languages_url }
      end
    end
  end
end

app/helpers/admin/languages_helper.rb
module Admin::LanguagesHelper
end

app/views/admin/languages/_form.html.haml
= semantic_form_for [:admin, @language] do |f|
  = f.semantic_errors
  = f.inputs do
    = f.input :name
    = f.input :description

    .word_fields
      - @language.errors['words.match_word'].each do |e|
        = "Match word " + e
      - @language.words.each do |word|
        = f.fields_for :language_words, word do |word_form|
          = render :partial => "word_fields", :locals => { :f => word_form }
      = link_to_add_fields("Add Word", f, :words)

  = f.buttons

:javascript
  function remove_fields(link) {
    $(link).prev("input[type=hidden]").val("1");
    $(link).closest(".fields").hide();
    $(link).parent().hide();
  }

  function add_fields(link, association, content) {
    var new_id = new Date().getTime();
    var regexp = new RegExp("new_" + association, "g");
    $(link).parent().before(content.replace(regexp, new_id));
  }

app/views/admin/languages/_sidebar.html.haml
.block.notice
  %h3 Simple Block
  .content
    %p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
.block
  %h3 Links
  %ul.navigation
    %li
      %a{:href => "#"} Link 1
    %li
      %a{:href => "#"} Link 2

app/views/admin/languages/_word_fields.html.haml
%p.fields
  = f.label :match_word
  = f.text_field :match_word
  = f.label :replacement_word
  = f.text_field :replacement_word
  = f.hidden_field :_destroy
  = link_to_function "remove", "remove_fields(this)"

app/views/admin/languages/edit.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", admin_languages_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_language_path
      %li.active= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_language_path
  .content
    %h2.title
      = t("web-app-theme.edit", :default => "Edit")
      Language
    .inner
      = render :partial => "form"
- content_for :sidebar, render(:partial => 'sidebar')

app/views/admin/languages/index.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first.active= link_to "#{t("web-app-theme.list", :default => "List")}", admin_languages_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_language_path
  .content
    %h2.title
      = t("web-app-theme.all", :default => "All")
      Languages
    .inner
      %table.table
        %tr
          %th.first ID
          %th
            = t("activerecord.attributes.admin_language.name", :default => t("activerecord.labels.name", :default => "Name"))
          %th= t("web-app-theme.created_at", :default => "Created at")
          %th.last &nbsp;
        - @languages.each do |language|
          %tr{:class => cycle("odd", "even")}
            %td
              = language.id
            %td
              = link_to language.name, admin_language_path(language)
            %td
              = language.created_at
            %td.last
              = link_to "#{t("web-app-theme.show", :default => "Show")}", admin_language_path(language)
              |
              \#{link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_language_path(language)} |
              \#{link_to "#{t("web-app-theme.delete", :default => "Delete")}", admin_language_path(language), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"}
      .actions-bar.wat-cf
        .actions
- content_for :sidebar, render(:partial => 'sidebar')

app/views/admin/languages/new.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", admin_languages_path
      %li.active= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_language_path
  .content
    %h2.title
      = t("web-app-theme.new", :default => "New")
      Language
    .inner
      = render :partial => "form"
- content_for :sidebar, render(:partial => 'sidebar')

app/views/admin/languages/show.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", admin_languages_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_language_path
      %li.active= link_to "#{t("web-app-theme.show", :default => "Show")}", admin_language_path
  .content
    .inner
      %p
        %b
          = t("activerecord.attributes.admin_language.name", :default => t("activerecord.labels.name", :default => "Name"))
          \:
        = @language.name
      %p
        %b
          = t("activerecord.attributes.admin_language.description", :default => t("activerecord.labels.description", :default => "Description"))
          \:
        = @language.description
      %p
        - if @language.words.count > 0
          %b
            Words
          %ul
            - @language.words.each do |word|
              %li
                = word.match_word
                \=>
                = word.replacement_word


      .wat-cf
        = link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_admin_language_path(@language), :class => "button"
        = link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), admin_language_path(@language), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"
- content_for :sidebar, render(:partial => 'sidebar')