config/routes.rb
Mormonizer::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  namespace :admin do
    root :to => "translations#index"
    resources :translations
    resources :users
    resources :languages
  end

  resources :translations
  root :to => "translations#index"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_roles
  has_many :roles, :through => :user_roles

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :role_ids

  def name
    self.email
  end

  def has_role?(role_sym)
    roles.any? { |r| r.name.underscore.to_sym == role_sym }
  end

  def self.find_for_facebook_oauth(access_token, signed_in_resource=nil)
    data = access_token['extra']['user_hash']
    if user = User.find_by_email(data["email"])
      user
    else # Create a user with a stub password.
      User.create(:email => data["email"], :password => Devise.friendly_token[0,20])
    end
  end

  # note that this uses screen_name instead of email
  def self.find_for_twitter_oauth(access_token, signed_in_resource=nil)
    data = access_token['extra']['user_hash']
    if user = User.find_by_email(data["screen_name"])
      user
    else # Create a user with a stub password.
      u = User.create(:email => data["screen_name"], :password => Devise.friendly_token[0,20])
      u.save
    end
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < ApplicationController
    load_and_authorize_resource
    # GET /users
    def index
      @users = User.all

      respond_to do |format|
        format.html # index.html.erb
      end
    end

    # GET /users/1
    def show
      @user = User.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
      end
    end

    # GET /users/1/edit
    def edit
      @user = User.find(params[:id])
    end

    # PUT /users/1
    def update
      @user = User.find(params[:id])

      respond_to do |format|
        if @user.update_attributes(params[:user])
          format.html { redirect_to(admin_user_path(@user), :notice => 'User was successfully updated.') }
        else
          format.html { render :action => "edit" }
        end
      end
    end

    # DELETE /users/1
    def destroy
      @user = User.find(params[:id])
      @user.destroy

      respond_to do |format|
        format.html { redirect_to(admin_users_url) }
      end
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model
    @user = User.find_for_facebook_oauth(env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.facebook_data"] = env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
  
  def twitter 
    # You need to implement the method below in your model
    @user = User.find_for_twitter_oauth(env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Twitter"
      sign_in_and_redirect @user, :event => :authentication
    else
      # the extra subhash makes this bigger than the session can store
      session["devise.twitter_data"] = env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end
end

app/views/admin/users/_form.html.haml
= semantic_form_for [:admin, @user] do |f|
  = f.semantic_errors
  = f.inputs do
    = f.input :roles, :as => :check_boxes
  = f.buttons

app/views/admin/users/edit.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", admin_users_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_user_path
      %li.active= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_user_path
  .content
    %h2.title
      = t("web-app-theme.edit", :default => "Edit")
      User
    .inner
      = render :partial => "form"
- content_for :sidebar, render(:partial => 'sidebar')

app/views/admin/users/index.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first.active= link_to "#{t("web-app-theme.list", :default => "List")}", admin_users_path
  .content
    %h2.title
      = t("web-app-theme.all", :default => "All")
      Users
    .inner
      %table.table
        %tr
          %th.first ID
          %th
            = t("activerecord.attributes.admin_user.email", :default => t("activerecord.labels.email", :default => "Email"))
          %th Roles
          %th.last &nbsp;
        - @users.each do |user|
          %tr{:class => cycle("odd", "even")}
            %td
              = user.id
            %td
              = link_to user.email, admin_user_path(user)
            %td
              - if user.roles.length > 0
                %ul
                  - user.roles.each do |role|
                    %li= role.name
            %td.last
              = link_to "#{t("web-app-theme.show", :default => "Show")}", admin_user_path(user)
              |
              \#{link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_user_path(user)} |
              \#{link_to "#{t("web-app-theme.delete", :default => "Delete")}", admin_user_path(user), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"}
      .actions-bar.wat-cf
        .actions
- content_for :sidebar, render(:partial => 'sidebar')

app/views/admin/users/show.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", admin_users_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_user_path
      %li.active= link_to "#{t("web-app-theme.show", :default => "Show")}", admin_user_path
  .content
    .inner
      %p
        %b Roles:
        %ul
          - @user.roles.each do |role|
            %li= role.name
      %p
        %b
          = t("activerecord.attributes.admin_user.email", :default => t("activerecord.labels.email", :default => "Email"))
          \:
        = @user.email
      %p
        %b
          = t("activerecord.attributes.admin_user.encrypted_password", :default => t("activerecord.labels.encrypted_password", :default => "Encrypted password"))
          \:
        = @user.encrypted_password
      %p
        %b
          = t("activerecord.attributes.admin_user.reset_password_token", :default => t("activerecord.labels.reset_password_token", :default => "Reset password token"))
          \:
        = @user.reset_password_token
      %p
        %b
          = t("activerecord.attributes.admin_user.reset_password_sent_at", :default => t("activerecord.labels.reset_password_sent_at", :default => "Reset password sent at"))
          \:
        = @user.reset_password_sent_at
      %p
        %b
          = t("activerecord.attributes.admin_user.remember_created_at", :default => t("activerecord.labels.remember_created_at", :default => "Remember created at"))
          \:
        = @user.remember_created_at
      %p
        %b
          = t("activerecord.attributes.admin_user.sign_in_count", :default => t("activerecord.labels.sign_in_count", :default => "Sign in count"))
          \:
        = @user.sign_in_count
      %p
        %b
          = t("activerecord.attributes.admin_user.current_sign_in_at", :default => t("activerecord.labels.current_sign_in_at", :default => "Current sign in at"))
          \:
        = @user.current_sign_in_at
      %p
        %b
          = t("activerecord.attributes.admin_user.last_sign_in_at", :default => t("activerecord.labels.last_sign_in_at", :default => "Last sign in at"))
          \:
        = @user.last_sign_in_at
      %p
        %b
          = t("activerecord.attributes.admin_user.current_sign_in_ip", :default => t("activerecord.labels.current_sign_in_ip", :default => "Current sign in ip"))
          \:
        = @user.current_sign_in_ip
      %p
        %b
          = t("activerecord.attributes.admin_user.last_sign_in_ip", :default => t("activerecord.labels.last_sign_in_ip", :default => "Last sign in ip"))
          \:
        = @user.last_sign_in_ip
      .wat-cf
        = link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_admin_user_path(@user), :class => "button"
        = link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), admin_user_path(@user), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"
- content_for :sidebar, render(:partial => 'sidebar')