config/routes.rb
Mormonizer::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  namespace :admin do
    root :to => "translations#index"
    resources :translations
    resources :users
    resources :languages
  end

  resources :translations
  root :to => "translations#index"
end

app/models/translation.rb
class Translation < ActiveRecord::Base
  belongs_to :user
  belongs_to :language

  before_validation :translate_input_text

  validates_presence_of :user_id, :language_id, :input_text, :output_text

  # Translates the input text and stores it to the output text
  # At some point, it will do the actual translation, for now it does nothign
  def translate_input_text
    if self.language
      self.output_text = self.language.translate(self.input_text)
    else
      self.output_text = self.input_text
    end
  end
end

app/controllers/admin/translations_controller.rb
module Admin
  class TranslationsController < ApplicationController
    load_and_authorize_resource

    # GET /translations
    # GET /translations.json
    def index
      @translations = Translation.all

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @translations }
      end
    end

    # GET /translations/1
    # GET /translations/1.json
    def show
      @translation = Translation.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @translation }
      end
    end

    # GET /translations/new
    # GET /translations/new.json
    def new
      @translation = Translation.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @translation }
      end
    end

    # GET /translations/1/edit
    def edit
      @translation = Translation.find(params[:id])
    end

    # POST /translations
    # POST /translations.json
    def create
      @translation = Translation.new(params[:translation])

      respond_to do |format|
        if @translation.save
          format.html { redirect_to admin_translation_path(@translation), notice: 'Translation was successfully created.' }
          format.json { render json: admin_translation_path(@translation), status: :created, location: @translation }
        else
          format.html { render action: "new" }
          format.json { render json: @translation.errors, status: :unprocessable_entity }
        end
      end
    end

    # PUT /translations/1
    # PUT /translations/1.json
    def update
      @translation = Translation.find(params[:id])

      respond_to do |format|
        if @translation.update_attributes(params[:translation])
          format.html { redirect_to admin_translation_path(@translation), notice: 'Translation was successfully updated.' }
          format.json { head :ok }
        else
          format.html { render action: "edit" }
          format.json { render json: @translation.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /translations/1
    # DELETE /translations/1.json
    def destroy
      @translation = Translation.find(params[:id])
      @translation.destroy

      respond_to do |format|
        format.html { redirect_to admin_translations_url }
        format.json { head :ok }
      end
    end
  end
end

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController
  def index
    @translation = Translation.new

    respond_to do |format|
      format.html
    end
  end

  def create
    @translation = Translation.new(params[:translation])
    @translation.user = current_user

    respond_to do |format|
      if @translation.save
        format.json { render :json => {:output_text => @translation.output_text } }
      else
        format.json { render :json => {:output_text => "There were errors in the form" } }
      end
    end
  end
end

app/helpers/translations_helper.rb
module TranslationsHelper
end

app/views/admin/translations/_form.html.haml
.group
  = f.label :user_id, t("activerecord.attributes.translation.user_id", :default => "User"), :class => :label
  = f.number_field :user_id, :class => 'number_field'
  %span.description Ex: a simple text
.group
  = f.label :language_id, t("activerecord.attributes.translation.language_id", :default => "Language"), :class => :label
  = f.number_field :language_id, :class => 'number_field'
  %span.description Ex: a simple text
.group
  = f.label :input_text, t("activerecord.attributes.translation.input_text", :default => "Input text"), :class => :label
  = f.text_area :input_text, :class => 'text_area'
  %span.description Ex: a simple text
.group
  = f.label :output_text, t("activerecord.attributes.translation.output_text", :default => "Output text"), :class => :label
  = f.text_area :output_text, :class => 'text_area'
  %span.description Ex: a simple text
.group.navform.wat-cf
  %button.button{:type => "submit"}
    = image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}")
    = t("web-app-theme.save", :default => "Save")
  %span.text_button_padding= t("web-app-theme.or", :default => "or")
  = link_to t("web-app-theme.cancel", :default => "Cancel"), admin_translations_path, :class => "text_button_padding link_button"

app/views/admin/translations/edit.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", admin_translations_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_translation_path
      %li.active= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_translation_path
  .content
    %h2.title
      = t("web-app-theme.edit", :default => "Edit")
      Translation
    .inner
      = form_for @translation, :url => admin_translation_path(@translation), :html => { :class => :form } do |f|
        = render :partial => "form", :locals => {:f => f}
- content_for :sidebar, render(:partial => 'sidebar')

app/views/admin/translations/index.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first.active= link_to "#{t("web-app-theme.list", :default => "List")}", admin_translations_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_translation_path
  .content
    %h2.title
      = t("web-app-theme.all", :default => "All")
      Translations
    .inner
      %table.table
        %tr
          %th.first ID
          %th
            = t("activerecord.attributes.admin_translation.user_id", :default => t("activerecord.labels.user_id", :default => "User_id"))
          %th= t("web-app-theme.created_at", :default => "Created at")
          %th.last &nbsp;
        - @translations.each do |translation|
          %tr{:class => cycle("odd", "even")}
            %td
              = translation.id
            %td
              = link_to translation.user_id, admin_translation_path(translation)
            %td
              = translation.created_at
            %td.last
              = link_to "#{t("web-app-theme.show", :default => "Show")}", admin_translation_path(translation)
              |
              \#{link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_translation_path(translation)} |
              \#{link_to "#{t("web-app-theme.delete", :default => "Delete")}", admin_translation_path(translation), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"}
      .actions-bar.wat-cf
        .actions
- content_for :sidebar, render(:partial => 'sidebar')

app/views/admin/translations/new.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", admin_translations_path
      %li.active= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_translation_path
  .content
    %h2.title
      = t("web-app-theme.new", :default => "New")
      Translation
    .inner
      = form_for :translation, :url => admin_translations_path, :html => { :class => :form } do |f|
        = render :partial => "form", :locals => {:f => f}
- content_for :sidebar, render(:partial => 'sidebar')

app/views/admin/translations/show.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", admin_translations_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_translation_path
      %li.active= link_to "#{t("web-app-theme.show", :default => "Show")}", admin_translation_path
  .content
    .inner
      %p
        %b
          = t("activerecord.attributes.admin_translation.user_id", :default => t("activerecord.labels.user_id", :default => "User"))
          \:
        = @translation.user_id
      %p
        %b
          = t("activerecord.attributes.admin_translation.language_id", :default => t("activerecord.labels.language_id", :default => "Language"))
          \:
        = @translation.language_id
      %p
        %b
          = t("activerecord.attributes.admin_translation.input_text", :default => t("activerecord.labels.input_text", :default => "Input text"))
          \:
        = @translation.input_text
      %p
        %b
          = t("activerecord.attributes.admin_translation.output_text", :default => t("activerecord.labels.output_text", :default => "Output text"))
          \:
        = @translation.output_text
      .wat-cf
        = link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_admin_translation_path(@translation), :class => "button"
        = link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), admin_translation_path(@translation), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"
- content_for :sidebar, render(:partial => 'sidebar')